MAX_PROMPT_LENGTH = 2_000
MAX_RESPONSE_LENGTH = 100_000
MAX_RESPONSE_PREVIEW_LENGTH = 240

DEFAULT_EVALUATION_DATASET_MAX_CASES = 50
DEFAULT_EVALUATION_DATASET_MAX_DECODED_BYTES = 49_152
DEFAULT_EVALUATION_MAX_WORKLOAD_QUERIES = 250

MAX_EVALUATION_DATASET_NAME_LENGTH = 100
MAX_EVALUATION_DATASET_DESCRIPTION_LENGTH = 300
MAX_EVALUATION_CASE_ID_LENGTH = 100
MAX_EVALUATION_CATEGORY_LENGTH = 100
MAX_EVALUATION_NOTE_LENGTH = 500
